<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$title = 'My movies';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('movie', array('action'=>'add'));?>">Add new movie</a>
 </p>

 <table class="table">
 <tr>
     <th>Title</th>
     <th>Director</th>
     <th>Year</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($movies as $movie) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($movie->title);?></td>
     <td><?php echo $this->escapeHtml($movie->director);?></td>
     <td><?php echo $this->escapeHtml($movie->date);?></td>
     <td>
         <a href="<?php echo $this->url('movie',
             array('action'=>'edit', 'id' => $movie->id));?>">Edit</a>
         <a href="<?php echo $this->url('movie',
             array('action'=>'delete', 'id' => $movie->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
